export const style ={
    container: {
        flex: 1,
        backgroundColor: '#0c0c0c',
        alignItems: 'center',
        justifyContent: 'center',
        //flexDirection: "row"
    },
    rowContainer: {
        //flex: 1,
        flexDirection: "row",
        //alignItems: "center",
        justifyContent: "center",
        backgroundColor: "#0c0c0c",
        width: "100vw",
        height: "80vh",
        marginTop: '1vh',

        paddingTop: '2vh',
        paddingBottom: '2vh',
    },
    containerColores: {
        backgroundColor: '#191919',
        flexDirection: "column",
        marginHorizontal: '2vw',
        height: "100%",
        width: "55%",
        alignItems: 'center',
        justifyContent: 'center',
        alignItems: 'center',
        borderWidth: 2,
        borderColor: '#ff002e',
        
        
    },
    listaColores: {
        flex:1,
        display: "flex",
        flexDirection: "row",
        flexWrap: "wrap",
        gap: "2vw",
        padding: "2vw",
        backgroundColor: "#191919",
        width: "100%",
        justifyContent: 'center',
        alignItems: 'center',
    },
    containerJugadores: {
        backgroundColor: '#ff002e',
        flexDirection: "column",
        marginHorizontal: '2vw',
        height: "100%",
        width: "25%",
        alignItems: 'center',
        borderRadius: 10,
    },
    jugadoresScroll: {
        backgroundColor: '#191919',
        width: "100%",
        flexWrap: "wrap",
        paddingVertical: '1vh',
    },
    colorCard: {
        //width: 250,
        minWidth: '3vw',
        flex: '0 0 18%',
        justifyContent: 'center',
        alignItems: 'center',
        flexDirection: "row",
        height: '4vw',
        borderRadius: 100,
        margin: 2,
    },
    tarjetaJugador: {
        backgroundColor: "white",
        alignContent: "center",
        flexDirection: "row",
        //justifyContent: "center",
        alignItems: "center",
        borderRadius: 10,
        marginVertical: 10,
        marginHorizontal: 15,
        paddingHorizontal: 15,
        height: '8vh',
    },
    selectorColores: {
        flexDirection: "row",
        flexWrap: "wrap",
        justifyContent: "center",
    }, 

    botonInicio: {
        backgroundColor: "green",
        width: "40vh",
        height: "5vh",
        borderRadius: 10,
        justifyContent: "center",
        alignItems: "center",
    },
    fila: {
        flexDirection: "row",
        justifyContent: "center",
        alignItems: "center",
        backgroundColor: "White",
        width: "100%",
        height: "4%",
    },
    celda: {
        //borderWidth: 1,
        borderColor: "black",
        width: '4%',
        height: '100%',
        justifyContent: "center",
        alignItems: "center",
        
    },
    imagenCelda: {
        width: '100%',
        height: '100%',
        position: "absolute",
        resizeMode: "stretch",
    },

    tablero: {
        //borderWidth: 1,
        borderColor: "black",
        justifyContent: "center",
        alignItems: "center",
        position: 'absolute',
        width: '100%',
        height: '100%',
    },

    //ficha circular
    celdaFicha: {
        //borderWidth: 1,
        borderColor: "black",
        width: '55%',
        aspectRatio: 1,
        justifyContent: "center",
        alignItems: "center",
        //backgroundColor: usuario.getFicha().color,
        borderRadius: 1000,
    },

}